services:
  backend:
    build: ./pb-back
    environment:
      HOST: shared-mysql # ★ 메인 DB의 컨테이너 이름으로 변경
      DBPWD: "rkwkrh13!#"
      SCHEMA: peakboard # (오타 수정 권장)
      PORT: 3050
    # depends_on: mysql 은 파일이 분리되었으므로 삭제해야 에러가 안 나!
    networks:
      - shared-network # 외부망 연결
      - default # 프론트와의 내부 통신용

  frontend:
    build: ./pb-front
    environment:
      PORT: 3030
    depends_on:
      - backend
    ports:
      - "3030:3030"
    networks:
      - default # 프론트는 백엔드하고만 통신하면 되니 굳이 shared-network에 안 넣어도 됨

networks:
  shared-network:
    external: true
